name: PostmanPat
version: '2.0.0'
main: me.zodd.postmanpat.PostmanPat
description: Postman
api-version: '1.21.1'
loader: me.zodd.postmanpat.mail.ExternalDependencyLoader
dependencies:
  server:
    Essentials:
      load: BEFORE
      required: true
    DiscordSRV:
        load: BEFORE
        required: true
    Vault:
        load: BEFORE
        required: true
